### ISSUE TITLE
broken links in documentation

### ISSUE THREAD

**Issue by cmellazchy** [jborean93/ansibug#22]
1. Documentation links in the README still redirect to the old site (https://jborean93.github.io/ansibug/) which is no longer reachable.  

   https://github.com/ansible-community/ansibug/blob/4b618213bec364507543a92743a56509a6cfa83b/README.md?plain=1#L9
   https://github.com/ansible-community/ansibug/blob/4b618213bec364507543a92743a56509a6cfa83b/README.md?plain=1#L18
   https://github.com/ansible-community/ansibug/blob/4b618213bec364507543a92743a56509a6cfa83b/README.md?plain=1#L20  

2. The `ansibug` header in the new docs site (https://ansible-community.github.io/ansibug/) still redirects to the older unreachable site.
3. The GIF uploaded for the REPL - Template section is incorrect. (`repl_template.gif`)

**Comment by jborean93** [comment]
Thanks, I'm in the process of redirecting it to my old namespace so the links should start working again. I'll push a fix for the incorrect gif as well.
